# Full Example: Home Assistant MQTT Sensors for Netgear CM1200
# This file creates a sensor for every channel (assuming 32 downstream, 8 upstream, 2 OFDM, and 2 OFDMA channels).
# Adjust channel counts if your modem exposes a different number.

sensor:
  # Downstream SNR per channel (1-32)
{% for i in range(1, 33) %}
  - platform: mqtt
    name: "CM1200 Downstream SNR Channel {{i}}"
    state_topic: "homeassistant/cm1200/ds_snr/channel_{{i}}"
    unit_of_measurement: "dB"
{% endfor %}

  # Downstream Power per channel (1-32)
{% for i in range(1, 33) %}
  - platform: mqtt
    name: "CM1200 Downstream Power Channel {{i}}"
    state_topic: "homeassistant/cm1200/ds_power/channel_{{i}}"
    unit_of_measurement: "dBmV"
{% endfor %}

  # Downstream Frequencies per channel (1-32)
{% for i in range(1, 33) %}
  - platform: mqtt
    name: "CM1200 Downstream Frequency Channel {{i}}"
    state_topic: "homeassistant/cm1200/ds_frequencies/channel_{{i}}"
    unit_of_measurement: "Hz"
{% endfor %}

  # Upstream Power per channel (1-8)
{% for i in range(1, 9) %}
  - platform: mqtt
    name: "CM1200 Upstream Power Channel {{i}}"
    state_topic: "homeassistant/cm1200/us_power/channel_{{i}}"
    unit_of_measurement: "dBmV"
{% endfor %}

  # Upstream Frequencies per channel (1-8)
{% for i in range(1, 9) %}
  - platform: mqtt
    name: "CM1200 Upstream Frequency Channel {{i}}"
    state_topic: "homeassistant/cm1200/us_frequencies/channel_{{i}}"
    unit_of_measurement: "Hz"
{% endfor %}

  # OFDM Downstream (2 channels)
{% for i in range(1, 3) %}
  - platform: mqtt
    name: "CM1200 OFDM Downstream Power Channel {{i}}"
    state_topic: "homeassistant/cm1200/ofdm_power/channel_{{i}}"
    unit_of_measurement: "dBmV"
  - platform: mqtt
    name: "CM1200 OFDM Downstream SNR Channel {{i}}"
    state_topic: "homeassistant/cm1200/ofdm_snr/channel_{{i}}"
    unit_of_measurement: "dB"
{% endfor %}

  # OFDMA Upstream (2 channels)
{% for i in range(1, 3) %}
  - platform: mqtt
    name: "CM1200 OFDMA Upstream Power Channel {{i}}"
    state_topic: "homeassistant/cm1200/ofdma_power/channel_{{i}}"
    unit_of_measurement: "dBmV"
{% endfor %}

  # Startup/System Status
  - platform: mqtt
    name: "CM1200 Downstream Channel Status"
    state_topic: "homeassistant/cm1200/downstream_channel_status"
  - platform: mqtt
    name: "CM1200 Connectivity State"
    state_topic: "homeassistant/cm1200/connectivity_state"
  - platform: mqtt
    name: "CM1200 Boot State"
    state_topic: "homeassistant/cm1200/boot_state"
  - platform: mqtt
    name: "CM1200 Security Status"
    state_topic: "homeassistant/cm1200/security_status"
  - platform: mqtt
    name: "CM1200 System Uptime"
    state_topic: "homeassistant/cm1200/system_uptime"

  # (Optional) All stats as JSON (for dashboards, templates, etc)
  - platform: mqtt
    name: "CM1200 All Stats"
    state_topic: "homeassistant/cm1200/all"
    value_template: "{{ value_json.system_uptime }}"
    json_attributes_topic: "homeassistant/cm1200/all"